/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

export default function LoginTest(props) {
  return (
    <div className="border bg-zinc-900 flex flex-col justify-center items-stretch px-16 py-12 border-solid border-neutral-300 max-md:px-5">
      <div className="mt-24 mb-16 mx-3 max-md:max-w-full max-md:mr-2.5 max-md:my-10">
        <div className="gap-5 flex max-md:flex-col max-md:items-stretch max-md:gap-0">
          <div className="flex flex-col items-stretch w-[45%] max-md:w-full max-md:ml-0">
            <div className="flex flex-col my-auto max-md:mt-10">
              <div className="text-gray-100 text-center text-3xl font-bold leading-10 self-center whitespace-nowrap">
                Login{" "}
              </div>
              <div className="justify-center bg-gray-100 self-stretch flex flex-col mt-10 pl-3 pr-20 py-2 rounded-md items-start max-md:mx-1.5 max-md:pr-5">
                <div className="text-gray-700 text-sm font-bold leading-6 whitespace-nowrap">
                  Email
                </div>
                <div className="text-neutral-300 text-sm leading-6 whitespace-nowrap mt-3">
                  example.email@gmail.com
                </div>
              </div>
              <div className="bg-gray-100 self-stretch flex justify-between gap-5 mt-7 px-3 py-2 rounded-md items-start max-md:mx-1.5">
                <div className="flex grow basis-[0%] flex-col items-stretch">
                  <div className="text-gray-700 text-sm font-bold leading-6 whitespace-nowrap">
                    Password
                  </div>
                  <div className="text-neutral-300 text-sm leading-6 whitespace-nowrap mt-3">
                    Enter at least 8+ characters{" "}
                  </div>
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/ed76ec9cf70b26db1216015f79e63952e47af4bde7fcbbda83e22846ae7cc87f?"
                  className="aspect-square object-contain object-center w-4 overflow-hidden shrink-0 max-w-full mt-5 self-end"
                />
              </div>
              <div className="text-slate-100 text-base leading-7 capitalize whitespace-nowrap justify-center items-center shadow-2xl self-stretch mt-12 px-16 py-4 rounded-lg max-md:mt-10 max-md:px-5">
                Sign in
              </div>
            </div>
          </div>
          <div className="flex flex-col items-stretch w-[55%] ml-5 max-md:w-full max-md:ml-0">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/720cc4047b50e4f24e7ca97a844dc6c5dae6b8294fa175a0a05246035ff9587c?"
              className="aspect-[1.35] object-contain object-center w-full fill-zinc-100 overflow-hidden grow max-md:max-w-full max-md:mt-9"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
